### ISSUE TITLE
puisance.py is cheating

### ISSUE THREAD

**Issue by Omykronn** [Astroow/Info-PSIET#1]
Y'a un bug dans le programme puissance.py, il dit avoit gagner alors que non

![Screenshot at 2023-02-01 20-58-51](https://user-images.githubusercontent.com/58723079/216150095-2048ffbc-1164-4b13-a833-cad8bdb36dfe.png)

**Comment by camillechaize** [comment]
Est ce qu'il serait possible d'enfin corriger ce bug ?! j'aimerai bien y jouer sans perdre parce que le bot cheat..
